const colors = {
  light: {
    text: "#0A0A1A",
    tint: "#7C3AED",
    background: "#F0F0F8",
    foreground: "#0A0A1A",
    card: "#FFFFFF",
    cardForeground: "#0A0A1A",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#E8E8F8",
    secondaryForeground: "#1A1A2E",
    muted: "#E4E4F0",
    mutedForeground: "#6B6B90",
    accent: "#0EA5E9",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#D8D8EC",
    input: "#D8D8EC",
  },
  dark: {
    text: "#F0F0FF",
    tint: "#A78BFA",
    background: "#09090F",
    foreground: "#F0F0FF",
    card: "#13131C",
    cardForeground: "#F0F0FF",
    primary: "#8B5CF6",
    primaryForeground: "#FFFFFF",
    secondary: "#1A1A28",
    secondaryForeground: "#C4C4DC",
    muted: "#16162A",
    mutedForeground: "#6B6B90",
    accent: "#22D3EE",
    accentForeground: "#000000",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E1E32",
    input: "#1E1E32",
  },
  radius: 14,
};

export default colors;
