export type ToolCategory = "image" | "pdf" | "utility" | "creator";

export interface Tool {
  id: string;
  name: string;
  description: string;
  icon: string;
  iconSet: "Ionicons" | "MaterialCommunityIcons" | "Feather" | "MaterialIcons";
  category: ToolCategory;
  route: string;
  implemented: boolean;
  trending?: boolean;
  featured?: boolean;
}

export interface Category {
  id: ToolCategory;
  name: string;
  icon: string;
  iconSet: "Ionicons" | "MaterialCommunityIcons" | "Feather" | "MaterialIcons";
  gradientStart: string;
  gradientEnd: string;
  toolCount: number;
}

export const CATEGORIES: Category[] = [
  {
    id: "image",
    name: "Image Tools",
    icon: "image-outline",
    iconSet: "Ionicons",
    gradientStart: "#7C3AED",
    gradientEnd: "#4F46E5",
    toolCount: 14,
  },
  {
    id: "pdf",
    name: "PDF Tools",
    icon: "document-text-outline",
    iconSet: "Ionicons",
    gradientStart: "#DC2626",
    gradientEnd: "#9F1239",
    toolCount: 10,
  },
  {
    id: "utility",
    name: "Utility Tools",
    icon: "grid-outline",
    iconSet: "Ionicons",
    gradientStart: "#0EA5E9",
    gradientEnd: "#0284C7",
    toolCount: 9,
  },
  {
    id: "creator",
    name: "Creator Tools",
    icon: "sparkles-outline",
    iconSet: "Ionicons",
    gradientStart: "#F59E0B",
    gradientEnd: "#D97706",
    toolCount: 7,
  },
];

export const TOOLS: Tool[] = [
  // IMAGE TOOLS
  {
    id: "image-compressor",
    name: "Image Compressor",
    description: "Compress images with target KB control",
    icon: "arrow-collapse-all",
    iconSet: "MaterialCommunityIcons",
    category: "image",
    route: "image-compressor",
    implemented: true,
    trending: true,
    featured: true,
  },
  {
    id: "image-resizer",
    name: "Image Resizer",
    description: "Resize images to custom dimensions",
    icon: "resize",
    iconSet: "MaterialCommunityIcons",
    category: "image",
    route: "image-resizer",
    implemented: true,
    featured: true,
  },
  {
    id: "background-remover",
    name: "Background Remover",
    description: "Remove image backgrounds with AI",
    icon: "image-remove",
    iconSet: "MaterialCommunityIcons",
    category: "image",
    route: "background-remover",
    implemented: true,
    trending: true,
  },
  {
    id: "image-converter",
    name: "Image Converter",
    description: "Convert between JPG, PNG, WEBP",
    icon: "swap-horizontal",
    iconSet: "MaterialCommunityIcons",
    category: "image",
    route: "image-converter",
    implemented: true,
  },
  {
    id: "image-cropper",
    name: "Image Cropper",
    description: "Crop images with aspect ratio presets",
    icon: "crop",
    iconSet: "MaterialCommunityIcons",
    category: "image",
    route: "image-cropper",
    implemented: true,
  },
  {
    id: "passport-photo",
    name: "Passport Photo Maker",
    description: "Create passport photos with country presets",
    icon: "card-account-details-outline",
    iconSet: "MaterialCommunityIcons",
    category: "image",
    route: "passport-photo",
    implemented: true,
    trending: true,
  },
  {
    id: "signature-maker",
    name: "Signature Maker",
    description: "Draw and export your digital signature",
    icon: "draw",
    iconSet: "MaterialCommunityIcons",
    category: "image",
    route: "signature-maker",
    implemented: true,
    featured: true,
  },
  {
    id: "image-enhancer",
    name: "AI Image Enhancer",
    description: "Sharpen and denoise photos with AI",
    icon: "image-auto-adjust",
    iconSet: "MaterialCommunityIcons",
    category: "image",
    route: "image-enhancer",
    implemented: true,
    trending: true,
  },
  {
    id: "image-upscaler",
    name: "AI Image Upscaler",
    description: "Upscale images 2x or 4x with AI",
    icon: "arrow-up-bold-box-outline",
    iconSet: "MaterialCommunityIcons",
    category: "image",
    route: "image-upscaler",
    implemented: true,
  },
  {
    id: "image-collage",
    name: "Image Collage Maker",
    description: "Create photo collages with layouts",
    icon: "collage",
    iconSet: "MaterialCommunityIcons",
    category: "image",
    route: "image-collage",
    implemented: true,
  },
  {
    id: "image-to-pdf",
    name: "Image to PDF",
    description: "Convert images to PDF documents",
    icon: "file-image",
    iconSet: "MaterialCommunityIcons",
    category: "image",
    route: "image-to-pdf",
    implemented: true,
  },
  {
    id: "target-resize",
    name: "Target File Size Resize",
    description: "Resize to exact KB for govt/exam forms",
    icon: "target",
    iconSet: "MaterialCommunityIcons",
    category: "image",
    route: "target-resize",
    implemented: true,
    trending: true,
  },
  {
    id: "govt-photo",
    name: "Govt Photo & Signature",
    description: "Passport and exam photo presets",
    icon: "badge-account-outline",
    iconSet: "MaterialCommunityIcons",
    category: "image",
    route: "govt-photo",
    implemented: true,
  },
  {
    id: "image-watermark",
    name: "Image Watermark",
    description: "Add text watermarks with position & opacity control",
    icon: "watermark",
    iconSet: "MaterialCommunityIcons",
    category: "image",
    route: "image-watermark",
    implemented: true,
    trending: true,
  },
  // PDF TOOLS
  {
    id: "pdf-merge",
    name: "PDF Merge",
    description: "Merge multiple PDFs into one",
    icon: "merge",
    iconSet: "MaterialCommunityIcons",
    category: "pdf",
    route: "pdf-merge",
    implemented: true,
    trending: true,
    featured: true,
  },
  {
    id: "pdf-split",
    name: "PDF Split",
    description: "Split PDF by page range",
    icon: "call-split",
    iconSet: "MaterialIcons",
    category: "pdf",
    route: "pdf-split",
    implemented: true,
  },
  {
    id: "pdf-compressor",
    name: "PDF Compressor",
    description: "Compress PDF to target size",
    icon: "file-download-outline",
    iconSet: "MaterialCommunityIcons",
    category: "pdf",
    route: "pdf-compressor",
    implemented: true,
    trending: true,
  },
  {
    id: "pdf-target-resize",
    name: "PDF Target Resize",
    description: "Resize PDF to exact KB/MB",
    icon: "file-percent-outline",
    iconSet: "MaterialCommunityIcons",
    category: "pdf",
    route: "pdf-target-resize",
    implemented: true,
    trending: true,
  },
  {
    id: "pdf-rotate",
    name: "PDF Rotate",
    description: "Rotate PDF pages",
    icon: "rotate-right",
    iconSet: "MaterialCommunityIcons",
    category: "pdf",
    route: "pdf-rotate",
    implemented: true,
  },
  {
    id: "pdf-watermark",
    name: "PDF Watermark",
    description: "Add text or image watermarks",
    icon: "watermark",
    iconSet: "MaterialCommunityIcons",
    category: "pdf",
    route: "pdf-watermark",
    implemented: true,
  },
  {
    id: "pdf-protect",
    name: "PDF Protect",
    description: "Add password protection to PDF",
    icon: "file-lock-outline",
    iconSet: "MaterialCommunityIcons",
    category: "pdf",
    route: "pdf-protect",
    implemented: true,
  },
  {
    id: "pdf-unlock",
    name: "PDF Unlock",
    description: "Remove PDF password protection",
    icon: "file-lock-open-outline",
    iconSet: "MaterialCommunityIcons",
    category: "pdf",
    route: "pdf-unlock",
    implemented: true,
  },
  {
    id: "pdf-to-image",
    name: "PDF to Image",
    description: "Convert PDF pages to JPG/PNG",
    icon: "file-image-outline",
    iconSet: "MaterialCommunityIcons",
    category: "pdf",
    route: "pdf-to-image",
    implemented: true,
  },
  {
    id: "doc-to-pdf",
    name: "Document to PDF",
    description: "Convert documents to PDF",
    icon: "file-export-outline",
    iconSet: "MaterialCommunityIcons",
    category: "pdf",
    route: "doc-to-pdf",
    implemented: true,
  },
  // UTILITY TOOLS
  {
    id: "qr-generator",
    name: "QR Generator",
    description: "Generate QR codes from any text or URL",
    icon: "qrcode",
    iconSet: "MaterialCommunityIcons",
    category: "utility",
    route: "qr-generator",
    implemented: true,
    trending: true,
    featured: true,
  },
  {
    id: "color-picker",
    name: "Color Picker",
    description: "Pick colors and get hex/RGB values",
    icon: "palette-outline",
    iconSet: "MaterialCommunityIcons",
    category: "utility",
    route: "color-picker",
    implemented: true,
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate and beautify JSON",
    icon: "code-json",
    iconSet: "MaterialCommunityIcons",
    category: "utility",
    route: "json-formatter",
    implemented: true,
  },
  {
    id: "base64-tool",
    name: "Base64 Encode/Decode",
    description: "Encode and decode Base64 text",
    icon: "code-braces",
    iconSet: "MaterialCommunityIcons",
    category: "utility",
    route: "base64-tool",
    implemented: true,
  },
  {
    id: "word-counter",
    name: "Word Counter",
    description: "Count words, chars, and reading time",
    icon: "counter",
    iconSet: "MaterialCommunityIcons",
    category: "utility",
    route: "word-counter",
    implemented: true,
    featured: true,
  },
  {
    id: "text-formatter",
    name: "Text Formatter",
    description: "Transform text case and formatting",
    icon: "format-text",
    iconSet: "MaterialCommunityIcons",
    category: "utility",
    route: "text-formatter",
    implemented: true,
  },
  {
    id: "unit-converter",
    name: "Unit Converter",
    description: "Convert units for length, weight, temp",
    icon: "ruler-square",
    iconSet: "MaterialCommunityIcons",
    category: "utility",
    route: "unit-converter",
    implemented: true,
  },
  {
    id: "file-size-analyzer",
    name: "File Size Analyzer",
    description: "Analyze storage and file sizes",
    icon: "chart-pie-outline",
    iconSet: "MaterialCommunityIcons",
    category: "utility",
    route: "file-size-analyzer",
    implemented: true,
  },
  {
    id: "qr-scanner",
    name: "QR Scanner",
    description: "Scan QR codes with camera",
    icon: "qrcode-scan",
    iconSet: "MaterialCommunityIcons",
    category: "utility",
    route: "qr-scanner",
    implemented: true,
    trending: true,
  },
  // CREATOR TOOLS
  {
    id: "caption-generator",
    name: "Caption Generator",
    description: "Generate captions for social media",
    icon: "comment-text-outline",
    iconSet: "MaterialCommunityIcons",
    category: "creator",
    route: "caption-generator",
    implemented: true,
    trending: true,
    featured: true,
  },
  {
    id: "hashtag-generator",
    name: "Hashtag Generator",
    description: "Generate trending hashtags for posts",
    icon: "pound",
    iconSet: "MaterialCommunityIcons",
    category: "creator",
    route: "hashtag-generator",
    implemented: true,
    trending: true,
  },
  {
    id: "youtube-title",
    name: "YouTube Title Generator",
    description: "Create click-worthy video titles",
    icon: "youtube",
    iconSet: "MaterialCommunityIcons",
    category: "creator",
    route: "youtube-title",
    implemented: true,
  },
  {
    id: "bio-generator",
    name: "Bio Generator",
    description: "Write compelling social media bios",
    icon: "account-edit-outline",
    iconSet: "MaterialCommunityIcons",
    category: "creator",
    route: "bio-generator",
    implemented: true,
  },
  {
    id: "prompt-generator",
    name: "Prompt Generator",
    description: "Generate AI art and chat prompts",
    icon: "robot-outline",
    iconSet: "MaterialCommunityIcons",
    category: "creator",
    route: "prompt-generator",
    implemented: true,
    trending: true,
  },
  {
    id: "social-toolkit",
    name: "Social Media Toolkit",
    description: "Complete toolkit for social creators",
    icon: "share-variant-outline",
    iconSet: "MaterialCommunityIcons",
    category: "creator",
    route: "social-toolkit",
    implemented: true,
  },
  {
    id: "thumbnail-utils",
    name: "Thumbnail Utilities",
    description: "Optimize YouTube thumbnails",
    icon: "image-filter-drama",
    iconSet: "MaterialCommunityIcons",
    category: "creator",
    route: "thumbnail-utils",
    implemented: true,
  },
];

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return TOOLS.filter((t) => t.category === category);
}

export function getTrendingTools(): Tool[] {
  return TOOLS.filter((t) => t.trending);
}

export function getFeaturedTools(): Tool[] {
  return TOOLS.filter((t) => t.featured);
}

export function getToolById(id: string): Tool | undefined {
  return TOOLS.find((t) => t.id === id);
}

export function getCategoryColor(category: ToolCategory): string {
  const cat = CATEGORIES.find((c) => c.id === category);
  return cat?.gradientStart ?? "#7C3AED";
}
